<?php
return array (
  'WEB_NAME' => '廊坊会议展有限公司-技术部',
  'WEB_ENAME' => 'sheji',
  'SEO_TITLE' => '技术部',
  'SEO_ETITLE' => 'Kdesign',
  'SEO_KEYWORDS' => '技术与设计',
  'SEO_EKEYWORDS' => 'kelvinvt,kdesign',
  'SEO_DESCRIPTION' => '我们专注在线装逼。',
  'SEO_EDESCRIPTION' => 'Kdesign enterprise website management system for small and medium enterprises and the development of foreign trade has a simple to use, powerful, cost-effective, scalable, safe, good stability bilingual version of the system that can accelerate the speed of development of the corporate website and reduce development costs. allow different users to understand the basis of the language a little html, you can quickly build a personalized style and powerful English corporate website.',
  'WEB_LOGO' => '53007d5b00000.png',
  'WEB_URL' => 'http://sheji.zwork.top',
  'WEB_CONTACTS' => 'kelvinvt',
  'WEB_ECONTACTS' => 'kelvinvt',
  'WEB_EMAIL' => 'kelvinvt@qq.com',
  'WEB_TEL' => 'Contact our QQ',
  'WEB_PHONE' => 'Contact our QQ',
  'WEB_FAX' => 'Contact our QQ',
  'WEB_ADD' => 'CHINA·GUANGDONG',
  'WEB_EADD' => 'CHINA·GUANGDONG',
  'WEB_ICP' => 'ICP:123123',
  'WEB_COPYRIGHT' => 'COPYRIGHT 2016 KDESIGN™ <strong>D</strong>esign:Kelvinvt ALL RIGHTS RESERVED.',
  'WEB_ECOPYRIGHT' => 'COPYRIGHT 2016 KDESIGN™ <strong>D</strong>esign:Kelvinvt ALL RIGHTS RESERVED.',
  'WEB_COUNT' => '',
  'WEB_SHARE' => '<div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></div>
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"32"},"share":{}};with(document)0[(getElementsByTagName(\'head\')[0]||body).appendChild(createElement(\'script\')).src=\'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=\'+~(-new Date()/36e5)];</script>',
  'WEB_ESHARE' => '<div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="Share to QQ space"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="Micro-blog Sina"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="Share to micro-blog"></a><a href="#" class="bds_renren" data-cmd="renren" title="Share to everyone network"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="Share to WeChat"></a></div>
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"32"},"share":{}};with(document)0[(getElementsByTagName(\'head\')[0]||body).appendChild(createElement(\'script\')).src=\'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=\'+~(-new Date()/36e5)];</script>',
  'IS_EMAIL' => '0',
  'EMAIL_PORT' => '25',
  'EMAIL_HOST' => 'smtp.qq.com',
  'EMAIL_USERNAME' => 'kelvinvt@qq.com',
  'EMAIL_PASSWORD' => 'kelvinvt',
  'EMAIL_FROMNAME' => 'kelvinvt',
  'EMAIL_TO' => 'kelvinvt@qq.com',
  'SEND_WAY' => '1',
  'IS_ONLINE' => '1',
  'MSN_ACCOUNT' => 'kelvinvt@live.cn',
  'MSN_NAME' => 'kelvinvt',
  'SKYPE_ACCOUNT' => 'kelvinvt',
  'SKYPE_NAME' => 'kelvinvt',
  'QQ_ACCOUNT' => '15038883',
  'QQ_NAME' => '技术支持',
  'TAOBAO_ACCOUNT' => 'kelvinvt',
  '1688_ACCOUNT' => 'kelvinvt',
  'ALIBABA_ACCOUNT' => 'kelvinvt',
  'ALIBABA_NAME' => 'kelvinvt',
  'WEB_QRCODE' => '57c4fe1141505.png',
  'INDEX_NUM' => '8',
  'INDEX_TAGS' => '1',
  'LIST_PRONUM' => '8',
  'LIST_NEWNUM' => '10',
  'LIST_PHOTONUM' => '8',
  'LIST_DOWNNUM' => '8',
  'IS_WATER' => '1',
  'WATER_POSITION' => '9',
  'WATER_LOGO' => '',
  'WATER_ALPHA' => 100,
  'IS_TRANSLATE' => '0',
  'VERSION' => 'CEHJY_12.08_webapp',
  'CNEN' => 'cn',
);
?>